name: Prod Upgrade Release
on:
  schedule:
    # every Sunday at 11:00AM UTC
    - cron: '0 11 * * 0'
permissions:
  contents: write
jobs:
  prod_upgrade_release:
    uses: phpolar/github-workflows/.github/workflows/prod-upgrade-release.yml@v1
    secrets: inherit
